### ISSUE TITLE
Problème pour les données avec une variante saison ou avion

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-agribalyse#1]
Il y a deux particularités qui ne sont pas prises en compte dans l'app (et renvoie des valeurs fausses) :
- saisonnalité : pour la fraise et la tomate, il y a 3 données : 
  - de saison : code ABG =  code CIQUAL_1
  - hors saison : code ABG =  code CIQUAL_2
  - mix de consommation FR : code ABG =  code CIQUAL_3
- Transport par avion : Haricot vert importé par avion, et Mangue importée par avion : code ABG =  code CIQUAL_1 (ou _2 pour sans avion)

Il y a donc 10 lignes avec un code AGB =/= code CIQUAL. Pour autant, il semblerait que la recherche se fasse sur le code CIQUAL.
Ainsi, la recherche ne se fait pas sur toutes les lignes + les valeurs renvoyées ne sont pas les bonnes, ex. : 
- le haricot vert par avion (20061_1) renvoie la valeur sans avion (20061_2) : https://app.agribalyse.fr/aliments/20061
- la fraise de saison (13014_1) revoie la valeur de la fraise crue (13014_3) : https://app.agribalyse.fr/aliments/13014

Est-ce que le problème peut être réglé en cherchant directement dans les codes AGB ?

(Pour autant, les codes CIQUAL à afficher sur les fiches reste les mêmes 😄)

**Comment by JenniferStephan** [comment]
hola :) fichier de données corrigé pour les transports (ex de la [mangue](https://app.agribalyse.fr/aliments?search=mangue&order=alph_asc); [haricot](https://app.agribalyse.fr/aliments?search=haricot%20vert%20cru&order=alph_asc)) et saison (ex de la [fraise](https://app.agribalyse.fr/aliments?search=fraise%20crue&order=alph_asc); [tomate](https://app.agribalyse.fr/aliments?search=tomate%20crue&order=alph_asc))

**Comment by martinregner** [comment]
Top ! Il y a tout, merci @JenniferStephan 👍 

Par contre les codes CIQUAL ne sont plus les bons : normalement, pour les variantes (ex. les 3 fraises, ou les 2 haricots) les codes CIQUAL sont les mêmes (nutritionnellement c'est la même fraise, enfin en théorie, ça pourrait se discuter 😜 ). Par contre c'est bien 2 codes différents dans AGB.
Possible d'avoir le code CIQUAL sur les fiches (sans le dernier chiffre donc ?) ?

Pour les URL, est-ce que l'on pourrait garder le "_" pour séparer des variantes ? c'est juste que pour d'autres variantes qui pourrait arriver lors des prochaines màj, il pourrait y avoir recouvrement entre un code CIQUAL et une variante (ex. [1000](https://app.agribalyse.fr/aliments/1000?order=alph_asc), si on a une variante avec un 1 ça revoie vers [10001](https://app.agribalyse.fr/aliments/10001?order=alph_asc) ... c'est pas pareil).

**Comment by martinregner** [comment]
👍
