### ISSUE TITLE
dans la fiche detaillée aliment, modifier le texte 16 indicateurs et non pas 14

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ecolab-agribalyse#16]
Sans unité, plus le score est bas plus son impact sur l'environnement est faible. Ce score unique est une moyenne pondérée des **16 indicateurs** (voir tableau ci-dessous), calculé selon la méthodologie européenne « PEF » (Product Environmental Footprint).

![Capture d’écran 2020-11-27 à 16 09 08](https://user-images.githubusercontent.com/36134318/100462687-ea751200-30ca-11eb-94ad-d27168841d64.png)

**Comment by martinregner** [comment]
closed by #19
