### ISSUE TITLE
Problème de redirection app.agribalyse

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-agribalyse#22]
https://app.agribalyse.fr/ à rediriger vers https://www.agribalyse.fr/app

(http://app.agribalyse.fr/ fonctionne)

**Comment by florianpanchout** [comment]
@martinregner Je redirige toutes les pages app.agribalyse.fr sauf la home (exemple : https://app.agribalyse.fr/app). 

J'ai galéré ce matin à essayer de rediriger la home sans succès. Je m'y remet demain (13/01)

**Comment by florianpanchout** [comment]
Corrigé. J'en ai profité pour passer le site sur Netlify
