### ISSUE TITLE
Ajout phrase clarification affichage environnemental

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-agribalyse#23]
![image](https://user-images.githubusercontent.com/46482115/103638466-3da17680-4f4d-11eb-83e8-453bbb345907.png)

Ajouter une phrase en dessous du titre "Découvrez ... ", même taille de police que le bouton "Documentation et accès aux données"

> Ceci correspond aux données brutes ACV "Agribalyse" et ne correspond pas à un "[affichage environnemental](https://ecolab.gitbook.io/documentation-agribalyse/usage-des-donnees/information-environnementale)"

avec un lien sur "affichage environnemental" vers la doc : https://ecolab.gitbook.io/documentation-agribalyse/usage-des-donnees/information-environnementale

**Comment by florianpanchout** [comment]
C'est ...peu esthétique. Est il possible de le mettre en bas de l'écran orange ? (même niveau que la carotte mais à gauche)

**Comment by martinregner** [comment]
En effet. Plutôt ici donc ?
![image](https://user-images.githubusercontent.com/46482115/103658788-f7a7db00-4f6b-11eb-836a-61c2aac03e44.png)

**Comment by martinregner** [comment]
Parfait ! 👍
