### ISSUE TITLE
Modif texte données brutes ACV

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-agribalyse#29]
Petits retours sur ce texte. Serait-il possible : 
- de le modifier en :

> Cette application présente les résultats de la base de données Agribalyse, selon les indicateurs ACV. Ceci ne correspond pas à un affichage environnemental ou un « éco-score » pour le grand-public. 

- de le grossir un peu et le « remonter » si possible (ex au niveau du milieu de la carotte)
![image](https://user-images.githubusercontent.com/46482115/106128435-ae5c3d00-615f-11eb-9617-d5e0fb128967.png)

**Comment by martinregner** [comment]
Il faudrait garder le lien sur "affichage environnemental" : https://ecolab.gitbook.io/documentation-agribalyse/usage-des-donnees/information-environnementale

**Comment by florianpanchout** [comment]
C'est fait

**Comment by martinregner** [comment]
On me demande dans l'oreillette si tu peux le grossir un peu 😋 
Peut-être même taille que "Documentation et accès aux données" ?

**Comment by martinregner** [comment]
Désolé @florianpanchout, les grands chefs proposent plutôt :
![image](https://user-images.githubusercontent.com/46482115/106488607-286c2900-64b4-11eb-88e3-ed5ad3272cc4.png)
![image](https://user-images.githubusercontent.com/46482115/106488637-302bcd80-64b4-11eb-98ab-f9f4ce3114d1.png)
![image](https://user-images.githubusercontent.com/46482115/106488655-36ba4500-64b4-11eb-9ef8-cb36f5aaf90d.png)

Pourrais-tu le mettre dans cet ordre ? :)

**Comment by florianpanchout** [comment]
Done
