### ISSUE TITLE
Ajout texte ACV sur landing

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-agribalyse#30]
Sur la landing, ajouter le texte suivant en dessous du bouton « Information, condition d’usage etc. » : 

> Cette application présente les résultats de la base de données Agribalyse, selon les indicateurs ACV. Ceci ne correspond pas à un affichage environnemental ou un « éco-score » pour le grand-public.

**Comment by florianpanchout** [comment]
@martinregner Il me faut la traduction anglaise si je dois l'afficher sur la landing

**Comment by martinregner** [comment]
Eh voilà @florianpanchout :)

> This application shows the results of the Agribalyse database, according to LCA indicators. It does not show an environmental labelling nor an “eco-score” for the general public.

**Comment by martinregner** [comment]
Est-ce que tu peux garder les liens sur : 
- affichage environnemental : https://ecolab.gitbook.io/documentation-agribalyse/usage-des-donnees/information-environnementale
- environmental labelling : https://ecolab.gitbook.io/agribalyse-documentation-en/data-use/environmental-labelling

**Comment by florianpanchout** [comment]
C'est fait
