### ISSUE TITLE
Bug redirection agribalyse.fr

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-agribalyse#34]
Depuis le 1/02 16h30, agribalyse.fr redirige vers agribalyse.fr/documentation (le gitbook)

Il y a un problème d'affichage qui se reproduit à chaque connexion pour les utilisateurs qui sont venus sur le site avant cette redirection :
![image](https://user-images.githubusercontent.com/46482115/106604440-f0babb00-655f-11eb-8182-52dd5bbeb3c9.png)

Le problème disparait : 
- temporairement avec un ctrl+shift+R
- de manière permanente en allant supprimer les cookies Agribalyse.

Il y a-t-il un moyen que ce problème soit contourné sans action sur les cookies côté utilisateur ?

**Comment by florianpanchout** [comment]
Alors ce n'est pas simple à résoudre comme problème.

On utilise sur Agribalyse (et les autres simulateurs) un service worker. Ce qui permet aux app de fonctionner hors ligne et d'être installables. 

Le problème c'est qu'ici le service worker considère qu'on est hors ligne (vu qu'il n'arrive plus à accéder aux données). Donc il ne charge pas la page actuelle mais celle qu'il a en cache.

Je n'ai pas de solution propre pour corriger ça de notre côté. Ce que l'on pourrait faire c'est une redirection 301 depuis l'application Agribalyse, à minima le temps que le service worker soit désinstallé partout. Ce serait normalement transparent pour l'utilisateur.

**Comment by martinregner** [comment]
Pas sûr de tout comprendre @florianpanchout 😋 
En gros la redirection ferait qu'on ne passe même pas par cette page et que donc on arrive sur /documentation ?
Si c'est ça, c'est parfait c'est effectivement le but final :
- https://www.agribalyse.fr/ --> redirection vers le gitbook https://www.agribalyse.fr/documentation/
- app sur https://agribalyse.ademe.fr/

**Comment by martinregner** [comment]
Visiblement le problème reste sur le worker... Est-ce que la 301 est bien effective ?
@florianpanchout tu sais quand il s'éteindra / sa durée de vie une fois dans l'ordi ?

**Comment by florianpanchout** [comment]
Est ce que tu peux réessayer ? C'est normalement corrigé mais je test à l'aveugle n'ayant plus le problème chez moi.

On passe maintenant très rapidement par la recherche Agribalyse avant d'accéder à la documentation.

**Comment by martinregner** [comment]
Hehe, moi non plus j'avais plus le problème... je suis allé embêter un directeur qui m'avait dit ce matin qui l'avait : c'est bon c'est résolu ! 👍

**Comment by martinregner** [comment]
Toc toc, devine de quoi va parler ce commentaire @florianpanchout ? 😄 

Bon, le problème se ressert : cette fois-ci le pb ne se produit que sur Firefox (je l'ai vu en live sur l'écran de Vincent ^^)

Une dernière piste complémentaire ? Sinon tu sais quand le cookie va partir / sa durée de vie une fois dans l'ordi ? (prochaine étape : je l'aide à enlever les cookies Agribalyse ;)
