### ISSUE TITLE
changer url des aliments

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ecolab-agribalyse#4]
/code_agb/aliment

**Comment by JenniferStephan** [comment]
mettre code agb et nom aliments
actuellement /code_ciqual ce qui fait des articles ont la meme url car meme code

**Comment by JenniferStephan** [comment]
Fait avec code_agb et # nom de l'aliment (juste une info en plus)
ce qui fait que url avec juste /code_agb et /code_agb#nom_aliment marchent conjointement :)

ex pizza : https://app.agribalyse.fr/aliments/25435 et https://app.agribalyse.fr/aliments/25435#Pizza_jambon_fromage

(nota bene : mauvaise pratique de faire code_agb/nom_aliment car suppose arborescence, structure différente or code et nom aliment, même niveau de données)

![Capture d’écran 2020-11-09 à 09 42 13](https://user-images.githubusercontent.com/36134318/98519049-88b24c80-2270-11eb-9a5b-b7ded514749c.png)


Reste à faire, pour les code_agb des mangues, tomates, fraises, haricots, qui adaptent code ciqual en ajoutant un _, il faut autoriser le parsing du _ en tant que caractere valable ds le code. Je laisse donc l'issue ouverte

**Comment by martinregner** [comment]
👍
