### ISSUE TITLE
Redirection https://agribalyse.fr/

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-agribalyse#40]
Me revoilà avec les redirections sur AGB 🙄
Visiblement le https ne fonctionne toujours pas.

Est-ce que https://agribalyse.fr/ pourrait rediriger vers https://www.agribalyse.fr/documentation/ ?

**Comment by florianpanchout** [comment]
Je crois qu'il nous faut un serveur pour pouvoir y installer notre certificat ssl pour pouvoir rediriger le https. Ca nous reviendrais à 7€60 / mois via Gandi.

(Peut être que @laem pourra valider ou invalider ce que je dis, je n'étais pas très attentif pendant mes cours de réseau...)

**Comment by florianpanchout** [comment]
Je suis passé par l'hébergement Netlify pour faire tout ça. C'est corrigé

**Comment by martinregner** [comment]
Top !!
Et tant qu'on y est @florianpanchout , tu crois que tu pourrais aussi rediriger les app.agribalyse.fr vers agribalyse.ademe.fr/app ? :)

**Comment by florianpanchout** [comment]
C'est fait !

**Comment by martinregner** [comment]
Merci !! :)
