### ISSUE TITLE
Renouvellement certificat HTTPS Gitbook

### ISSUE THREAD

**Issue by fjg** [betagouv/ecolab-agribalyse#41]
On a reçu une alerte de Gitbook pour doc.agribalyse.fr qui dit

````
Your domain is set as proxied in your Cloudflare configuration. That's the orange cloud option. This means we cannot check if its CNAME value is set to hosting.gitbook.com. We recommend disabling the Cloudflare proxy. If that's not possible, please make sure your custom domain CNAME value is set to hosting.gitbook.com.
````
Ca c'est ok, le CNAME _doc.agribalyse.fr_ pointe bien vers _hosting.gitbook.com_.

```` 
It is necessary that all requests to the /.well-known prefix on your domain go through HTTP. It allows us to confirm your domain. You may have activated automatic HTTPS redirections. Please make sure all paths prefixed by /.well-known are not redirected back to HTTPS.
````

Sur ce point Florian, il faudrait donc conserver l'accès HTTP sur /.well-known. Tu peux modifier l'app pour faire ca ?

**Comment by florianpanchout** [comment]
Sauf erreur, la redirection https est faite au niveau de Gitbook. 
Je ne pense pas qu'il y ai de problème du coup.

**Comment by fjg** [comment]
c'est cloudflare qui fait la redirection effectivement... je ne comprends pas leur message du coup.

**Comment by fjg** [comment]
@martinregner a priori c'est gitbook qui a la main sur la config. On a les bons enregistrements DNS.
